apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-docs
  title: test-docs
  description: This is the documentation for testing
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: experimental
  owner: belurep
